### ISSUE TITLE
Create an implementation design, consisting of UML component, UML class and UML state diagram.

### ISSUE THREAD

**Issue by pavel-semenov-1** [TIS2021-FMFI/interferencia#10]

**Comment by eli1500** [comment]
a sketch of the uml state diagram was created and added to the Design Document.
<img width="510" alt="stateUML" src="https://user-images.githubusercontent.com/79512433/140918175-6e6683dc-fda6-437b-820b-bffb37fae052.png">

**Comment by pavel-semenov-1** [comment]
Suggested UML Component diagram contents:
***
Frontend:
Graph visualisation (receive data from calculations engine)
Input views (send data to calculations engine)
Output views (receive data from filesystem reader/writer, receive data from OpenCV camera controller, receive data from calculations engine)

Backend:
Calculations engine
OpenCV camera controller
Filesystem reader/writer (receive data from calculations engine)
