### ISSUE TITLE
Get the correct formulas

### ISSUE THREAD

**Issue by pavel-semenov-1** [TIS2021-FMFI/interferencia#12]
Needs further discussion with the client

**Comment by pavel-semenov-1** [comment]
### The client has provided some data to work with:

- [Spreadsheet](https://docs.google.com/spreadsheets/d/1QpmU2ItQRgKquqGDGDe22JDIx7EFJ2rX/edit?usp=sharing&ouid=117262793214357358696&rtpof=true&sd=true)
- [Document](https://docs.google.com/spreadsheets/d/1QpmU2ItQRgKquqGDGDe22JDIx7EFJ2rX/edit?usp=sharing&ouid=117262793214357358696&rtpof=true&sd=true)
- ![image](https://user-images.githubusercontent.com/69585842/140984262-5b0b5706-a246-4f65-adf3-c83c578fdc34.png)

**Comment by surikatka** [comment]
Client decided to re-make formulas because of possible mistakes he might have made.

**Comment by surikatka** [comment]
Client provided us new formulas, we understood part of it, need to clear the point cloud part with client.
