### ISSUE TITLE
Create a software requirements document

### ISSUE THREAD

**Issue by pavel-semenov-1** [TIS2021-FMFI/interferencia#8]

**Comment by pavel-semenov-1** [comment]
Google document was created. It is available [here](https://docs.google.com/document/d/1JKkjWh5TkAAhJJU1FZYHd4Uj16cvxYBUXJtjjb2biMM/edit?usp=sharing).

**Comment by pavelpetrovic** [comment]
odporucam dohodnut sa so zadavatelom ako riesit meranie lepsie, t.j. brat do uvahy geomtriu snimania obrazu a rozny pomer pixel/mm v roznych castiach obrazu, najlepsie by bolo pouzit specialny kalibracny obrazok, pomocou ktoreho sa zaroven nastavi pixel/cm ratio. odporucam vyzadovat fotenie v aparature, zistit, ci je mozne fotit kolmo, alebo ako inak.
