### ISSUE TITLE
Create GUI mock-ups.

### ISSUE THREAD

**Issue by pavel-semenov-1** [TIS2021-FMFI/interferencia#9]

**Comment by surikatka** [comment]
first (very basic) draft
![Screenshot from 2021-10-21 01-12-27](https://user-images.githubusercontent.com/79468997/138186355-d24a6762-a491-4139-9e81-a8c859ac87da.png)

**Comment by surikatka** [comment]
GUI 3.0
![Screenshot from 2021-11-04 22-35-32](https://user-images.githubusercontent.com/79468997/140423493-3aa8fcbe-58b8-491f-9631-83b8f0c1f494.png)

**Comment by surikatka** [comment]
![Screenshot from 2021-11-29 14-26-49](https://user-images.githubusercontent.com/79468997/143876400-0b637493-872a-46ce-a831-675b2313245a.png)

new gui updated with latest requirements
need to make sure we are going to do:
* line slider for custom line thickness
* radio button for choosing two different points or to place one point in the middle automatically and only choosing the second point
